### ISSUE TITLE
Loss收敛范围

### ISSUE THREAD

**Issue by qazwsx671713** [x-cls/superclass#10]
你好，我是用vit作为image encoder，gte作为text encoder，仅使用ClsLoss进行训练。

我的词典大小约为20w，lr遵循论文中的设定，设置为5e-4。

但最终我的Loss值大概从12降低到7左右就无法再下降了，想请教一下这是否正常，以及你们在训练时，Loss一般收敛到什么范围？

![1CD6DA29-88FB-443E-92F6-87898B2D7E35](https://github.com/user-attachments/assets/78511212-967f-43d0-9b02-4000b293c8b0)

**Comment by speedinghzl** [comment]
loss收敛的值与模型大小，训练数据和voc size都有关。
在我们的实验中datacomp，ViT-L，49k voc size的条件下，loss最终收敛在5-6附近的值。可供参考。
