### ISSUE TITLE
Great Work! Check Out Our Related Research

### ISSUE THREAD

**Issue by anxiangsir** [x-cls/superclass#3]
Your recent work on **superclass** is incredibly solid. The presentation is spot on, and the innovation is impressive. Kudos to you all!

We've been working on something similar but with a twist. Our approach uses more abstract cluster centers for labeling and incorporates multi-label techniques. It's been showing some great results.

We'd love for you to check out our work as well. Looking forward to any thoughts or feedback you might have!

https://github.com/deepglint/unicom?tab=readme-ov-file#multi-label-cluster-discrimination-mlcd

| Model Name | ImageNet Linear Probe | Hugging Face | Google Drive |
| :--        | :-:                   | :-:          | :-:          |
| MLCD-ViT-L-14-336px | 86.3 | [HF:MLCD-ViT-L-14-336px](https://huggingface.co/DeepGlint-AI/mlcd-vit-large-patch14-336) | - |
| MLCD-ViT-B-32-224px | 79.1 | [HF:MLCD-ViT-B-32-224px](https://huggingface.co/DeepGlint-AI/mlcd-vit-base-patch32-224) | - |

**Comment by speedinghzl** [comment]
@anxiangsir Thank you so much for your kind words on Superclass.
And thanks for bringing your work to us. The multi-label contrastive loss is cool.  The trained model with stronger zero-shot ability is impressive.
