### ISSUE TITLE
zeroshot OR eval on in1k

### ISSUE THREAD

**Issue by zhiwenhou1227** [x-cls/superclass#4]
请问有在in1k上zero-shot的代码吗，在.yaml文件里设置了如下参数：
zeroshot_steps: 1200000
val_steps: 1200000
zeroshot_frequency: 1
会有如下报错AttributeError: 'Classifier' object has no attribute 'encode_text'，请教下该如何适配呢

**Comment by zhiwenhou1227** [comment]
知道问题在哪里了，在训superclass的时候加入了zero shot导致的错误，如果想在in1k上进行zero shot，是不是必须得在训练下LiT部分？

**Comment by speedinghzl** [comment]
是的。需要LiT后再做zero-shot。
