### ISSUE TITLE
模型训练出来权重有多大

### ISSUE THREAD

**Issue by HuangHua123** [x-cls/superclass#6]

**Comment by dongdk** [comment]
will release the pretrained model?

**Comment by speedinghzl** [comment]
@HuangHua123 没没明白你的问题。我们有训练ViT-S、B、L模型，分别大约有20+,80+和300+M参数量。

**Comment by speedinghzl** [comment]
@dongdk We do not plan to release these models shortly. An upgraded version of the models is expected to be open-sourced in about 3-4 months. Thanks for your interest and stay tuned.
