### ISSUE TITLE
Questions about imagenet linear probing 

### ISSUE THREAD

**Issue by Jingfeng0705** [x-cls/superclass#9]
Hi authors! Thanks for the great work. I have a question for Mae-style finetuning. I noticed superclass uses global pool while training, and for global pool model MAE initialize both a projection head and a fc norm layer. I want to ask do superclass only add a head projection layer after post-layer norm layer while finetuning, or also initialize a fc norm layer? Is there any other modification to the superclass architecture while finetuning?

Also, does superclass use the linear probing recipe specified in MAE paper? Is there any future plan to release finetune scripts?

Thanks again for your great work!

**Comment by speedinghzl** [comment]
@Jingfeng0705 When performing linear probing, we drop the whole [ClsHead](https://github.com/x-cls/superclass/blob/main/opencls/open_clip/transformer.py#L858) and randomly initialized the norm + fc layer in the new head. The last [layernorm](https://github.com/x-cls/superclass/blob/main/opencls/open_clip/transformer.py#L436) in the backbone uses the pre-trained one.

We use [this repo](https://github.com/zejiangh/MILAN/blob/main/main_linprobe.py) for linear probing, which is also built upon MAE repo.
